id: I327F240D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:22:55+00:00'
last_modified: '2022-06-07T21:23:50.171783+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6156
  title: ཁེ་ལས་འཛུགས་གཉེར་གྱི་ཐབས་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    ED1E:
      image_group_id: I1KG8421
      title: ''
      total_pages: 126
      order: 1
      base_file: ED1E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
