id: P004248
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6156
  title: ཁེ་ལས་འཛུགས་གཉེར་གྱི་ཐབས་ལམ།
  author: ''
  volumes:
    c3ccdda3cde6445e85d76ef5651b0619:
      image_group_id: I1KG8421
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
